spring:
  application:
    name: sircip

  datasource:
    url: jdbc:postgresql://localhost:5432/sircip_db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  web:
    error:
      include-message: always
      include-binding-errors: always    # (Reemplaza a server.error.include-binding-errors)
      include-exception: false          # (Reemplaza a server.error.include-exception)
      include-stacktrace: never         # (Reemplaza a server.error.include-stacktrace)

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.zalando.logbook: TRACE

logbook:
  format:
    style: json
  obfuscate:
    headers:
      - Authorization
      - X-Api-Key