spring:
  application:
    name: sircip

  datasource:
    url: jdbc:postgresql://localhost:5432/sircip_db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  api-key: "MiClaveSecreta123"

